import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title:"Create Next App",
  description:"Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({children}: Readonly<RootLayoutProps>) {
  return (
    <html
      lang="pt-BR"  >

      <body className="qualquer">



        {children}

        <footer><h1><footer></footer></h1></footer>

        </body>
    </html>
  );
}
